name: Test
on:
  pull_request:
  push:
    branches:
      - "main"
jobs:
  codespell:
    runs-on: ubuntu-latest
    steps:
      - uses: codespell-project/actions-codespell@v2
        with:
          skip: lib/ffaker/data,REFERENCE.md
          ignore_words_list: nce,expresso

  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby:
          - '3.1'
          - '3.2'
          - '3.3'
          - '3.4'
    name: Ruby ${{ matrix.ruby }} test
    steps:
      - uses: actions/checkout@v3
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true # 'bundle install' and cache
      - run: bundle exec rake test
